/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOMCORMVISTSALLIS
#define ROOMCORMVISTSALLIS

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooMcorMvisTsallis : public RooAbsPdf {
   public:
      RooMcorMvisTsallis() {} ; 
      RooMcorMvisTsallis(const char *name, const char *title,
            RooAbsReal& _Mcor,
            RooAbsReal& _Mvis,
            RooAbsReal& _T,
            RooAbsReal& _n,
            RooAbsReal& _Lambda);
      RooMcorMvisTsallis(const RooMcorMvisTsallis& other, const char* name=0) ;
      virtual TObject* clone(const char* newname) const { return new RooMcorMvisTsallis(*this,newname); }
      inline virtual ~RooMcorMvisTsallis() { }

      Double_t evaluate() const ;
   protected:

      RooRealProxy Mcor ;
      RooRealProxy Mvis ;
      RooRealProxy T ;
      RooRealProxy n ;
      RooRealProxy Lambda ;



   private:

      // this class is used to represent the 2D distribution 
      //corrected mass x visible mass for combinatorial


      //the following functions are intermediate steps for the evaluate method:

      Double_t tsallis(Double_t& x) const;
      Double_t corMassAtFixedMTsallis() const;
      Double_t visMass1D() const;

};
#endif
